### ISSUE TITLE
Installation on OS X fails

### ISSUE THREAD

**Issue by timbuchwaldt** [project-fifo/pyfi#10]
The given error from pip install pyfi is
```error: [Errno 2] No such file or directory: '/Users/tim/.virtualenvs/fifo-ansible/build/pyfi/doc'```

**Comment by Licenser** [comment]
Sorry for that,
I split the man pages a while ago and forgot to adjust the manifest. Solved now.

**Comment by timbuchwaldt** [comment]
Ok, Cool! Thx :)
